version: "3.7"

services:
  # api:
  #   build:
  #     context: ./
  #     dockerfile: ./api/Dockerfile.dev
  #   ports:
  #     - ${PORT}:${PORT}
  #   links:
  #     - mongo
  #   volumes:
  #     - ./api:/api
  #     - /api/node_modules
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:5.0
    command: mongod --port ${DBPORT}
    ports:
      - "${DBPORT}:${DBPORT}"
    environment:
      MONGO_INITDB_DATABASE: "hello"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_PASSWORD_FILE: /run/secrets/mongo_password
      MONGO_USER: "user"
    secrets:
      - mongo_password
      - mongo_root_password
    volumes:
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongo:/data/db
  
secrets:
  mongo_password:
    file: ./secrets/mongo_password.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt