version: "3.7"

services:
  # api:
  #   build:
  #     context: ./
  #     dockerfile: ./api/Dockerfile.dev
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   links:
  #     - mongo
  #   volumes:
  #     - ./api:/api
  #     - /api/node_modules
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:5.0
    command: mongod --port ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_USER=${DB_USER}
      - MONGO_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongo:/data/db