version: "3.7"

services:
  # api:
  #   build:
  #     context: ./
  #     dockerfile: ./api/Dockerfile.dev
  #   ports:
  #     - ${PORT}:${PORT}
  #   links:
  #     - mongo
  #   volumes:
  #     - ./api:/api
  #     - /api/node_modules
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:5.0
    command: mongod --port ${DBPORT}
    ports:
      - "${DBPORT}:${DBPORT}"
    environment:
      - MONGO_INITDB_DATABASE=${DBNAME}
      - MONGO_INITDB_ROOT_USERNAME=${DBROOTUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${DBROOTPASSWORD}
      - MONGO_USER=${DBUSER}
      - MONGO_PASSWORD=${DBPASSWORD}
    volumes:
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongo:/data/db